class element():
    vdw = 2.0
    color = (1.0, 1.0, 1.0)
    mass = 1.0
    name = ""
    symbol = ""

    def __init__(self, vdw, col, m, n, s):
        self.vdw = vdw
        self.color = col
        self.mass = m
        self.name= n
        self.symbol = s

elements = {
  'h' : element(1.20, (1.0, 1.0, 1.0), 1.0, "Hydrogen", "h"),
  'c' : element(1.70, (0.2, 0.2, 0.2), 12.0, "Carbon", "c"),
  'n' : element(1.55, (0.0, 0.0, 1.0), 14.0, "Nitrogen", "n"),
  'o' : element(1.52, (1.0, 0.0, 0.0), 16.0, "Oxygen", "o")
}

symbols = [ "empty",
            "H",
            "He",
            "Li",
            "Be",
            "B",
            "C",
            "N",
            "O",
            "F",
            "Ne",
            "Na",
            "Mg",
            "Al",
            "Si",
            "P",
            "S",
            "Cl",
            "Ar",
            "K",
            "Ca",
            "Sc",
            "Ti",
            "V",
            "Cr",
            "Mn",
            "Fe",
            "Co",
            "Ni",
            "Cu",
            "Zn",
            "Ga",
            "Ge",
            "As",
            "Se",
            "Br",
            "Kr",
            "Rb",
            "Sr",
            "Y",
            "Zr",
            "Nb",
            "Mo",
            "Tc",
            "Ru",
            "Rh",
            "Pd",
            "Ag",
            "Cd",
            "In",
            "Sn",
            "Sb",
            "Te",
            "I",
            "Xe",
            "Cs",
            "Ba",
            "La",
            "Ce",
            "Pr",
            "Nd",
            "Pm",
            "Sm",
            "Eu",
            "Gd",
            "Tb",
            "Dy",
            "Ho",
            "Er",
            "Tm",
            "Yb",
            "Lu",
            "Hf",
            "Ta",
            "W",
            "Re",
            "Os",
            "Ir",
            "Pt",
            "Au",
            "Hg",
            "Tl",
            "Pb",
            "Bi",
            "Po",
            "At",
            "Rn",
            "Fr",
            "Ra",
            "Ac",
            "Th",
            "Pa",
            "U",
            "Np",
            "Pu",
            "Am",
            "Cm",
            "Bk",
            "Cf",
            "Es",
            "Fm",
            "Md",
            "No",
            "Lr",
            "Rf",
            "Db",
            "Sg",
            "Bh",
            "Hs",
            "Mt",
            "Ds",
            "Rg",
            "Cn",
            "Uut",
            "Fl",
            "Uup",
            "Lv",
            "Uus",
            "Uuo"
]
