# This workflow will install Python dependencies, run tests and lint with a variety of Python versions

name: Build

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

env:
  BLENDER_VERSION: "3.6.7"
  BLENDER_MAJOR_VERSION: "3.6"

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false

    steps:
    - uses: actions/checkout@v4
    - name: Set up Python 3.10
      uses: actions/setup-python@v3
      with:
        python-version: "3.10"
    - name: Install Linux Dependences
      run: |
        sudo apt-get update
        sudo apt-get install -y clang gcc blender tar xz-utils
    - name: Install Python Dependences
      run: |
        python -m pip install --upgrade pip
        python -m pip install -q pytest cython numpy
    - name: Install Blender 3.6
      run: |
        echo "Installing Blender ${BLENDER_VERSION}"
        wget -q "https://mirror.clarkson.edu/blender/release/Blender3.6/blender-${BLENDER_VERSION}-linux-x64.tar.xz"
        tar -xf blender-${BLENDER_VERSION}-linux-x64.tar.xz
    - name: Install molecular-blender addon
      run: |
        mkdir -p ${HOME}/.config/blender/${BLENDER_MAJOR_VERSION}/scripts/addons
        python setup.py build
        python setup.py install --copy
    - name: Test Blender
      run: |
        bash run_test.sh -b blender-${BLENDER_VERSION}-linux-x64/blender
