# This workflow will install Python dependencies, run tests and lint with a variety of Python versions

name: Build

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python 3.10
      uses: actions/setup-python@v3
      with:
        python-version: "3.10"
    - name: Install Linux Dependences
      run: |
        sudo apt-get update
        sudo apt-get install -y clang gcc blender
    - name: Install Python Dependences
      run: |
        python -m pip install --upgrade pip
        python -m pip install -q pytest cython
    - name: Install Blender 3.6
      run: |
        pytest
        export BLENDER_VERSION=3.6.7
        echo "Installing Blender ${BLENDER_VERSION}"
        wget "https://www.blender.org/download/release/Blender3.6/blender-${BLENDER_VERSION}-linux-x64.tar.xz"
        tar -xf blender-${BLENDER_VERSION}-linux-x64.tar.xz

        # set up path for blender
        export PATH=${PWD}/blender-${BLENDER_VERSOIN}-linux-x64

        # register addon
        export BLENDER_DIR=${HOME}/.config/blender/${BLENDER_VERSION}
        mkdir -p ${BLENDER_DIR}/scripts/addons
        echo \"{ \\\"Copy Target\\\" : \\\"${BLENDER_DIR}/scripts/addons\\\" }\" > conf.json
        python setup.py build --copy
    - name: Test Blender
      run: |
        ./run_test.sh -b blender-${BLENDER_VERSION}-linux-x64/blender
